services:
  app-db:
    image: postgres:12-alpine
    container_name: ${DB_DOCKER_CONTAINER}
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - app_db_data:/var/lib/postgresql/data
    networks:
      - app-network

  keycloak-db:
    image: postgres:12-alpine
    container_name: ${USERDB_DOCKER_CONTAINER}
    restart: always
    environment:
      POSTGRES_USER: ${USERDB_USER}
      POSTGRES_PASSWORD: ${USERDB_PASSWORD}
      POSTGRES_DB: ${USERDB_NAME}
    ports:
      - "${USERDB_PORT}:5432"
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    networks:
      - keycloak-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: ${KEYCLOAK_CONTAINER}
    restart: always
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/${USERDB_NAME}
      KC_DB_USERNAME: ${USERDB_USER}
      KC_DB_PASSWORD: ${USERDB_PASSWORD}
    ports:
      - "${KEYCLOAK_PORT}:8080"
    depends_on:
      - keycloak-db
    command: ["start-dev"]
    networks:
      - keycloak-network

volumes:
  app_db_data:
  keycloak_db_data:

networks:
  app-network:
  keycloak-network:

