services:
  griefdb:
    image: postgres:12-alpine
    container_name: ${DB_DOCKER_CONTAINER}
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - app_db_data:/var/lib/postgresql/data
    networks:
      - app-network

  userdb:
    image: postgres:12-alpine
    container_name: ${USERDB_DOCKER_CONTAINER}
    restart: always
    environment:
      POSTGRES_USER: ${USERDB_USER}
      POSTGRES_PASSWORD: ${USERDB_PASSWORD}
      POSTGRES_DB: ${USERDB_NAME}
    ports:
      - "${USERDB_PORT}:5432"
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    networks:
      - keycloak-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USERDB_USER} -d ${USERDB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: ${KEYCLOAK_CONTAINER}
    restart: always
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://userdb:5432/${USERDB_NAME}
      KC_DB_USERNAME: ${USERDB_USER}
      KC_DB_PASSWORD: ${USERDB_PASSWORD}
    ports:
      - "${KEYCLOAK_PORT}:8080"
    depends_on:
      userdb:
        condition: service_healthy
    command: ["start-dev"]
    networks:
      - keycloak-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_CLIENT_PORT:-2181}
    ports:
      - "2181:2181"
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: ${KAFKA_BROKER_ID:-1}
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:${ZOOKEEPER_CLIENT_PORT:-2181}"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - app-network

volumes:
  app_db_data:
  keycloak_db_data:

networks:
  app-network:
  keycloak-network:
